// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using madan.MVC.Data;

#nullable disable

namespace madan.MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("madan.MVC.Data.Models.CostCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CostCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Name = "هزینه عیدی"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Name = "هزینه بیمه مسئولیت"
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Name = "هزینه باربرگ"
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Name = "هزینه تعمیرات"
                        },
                        new
                        {
                            Id = 5L,
                            IsActive = true,
                            Name = "هزینه ملزومات اداری"
                        },
                        new
                        {
                            Id = 6L,
                            IsActive = true,
                            Name = "هزینه معدن"
                        },
                        new
                        {
                            Id = 7L,
                            IsActive = true,
                            Name = "هزینه بیمه ثالث"
                        },
                        new
                        {
                            Id = 8L,
                            IsActive = true,
                            Name = "هزینه سوخت"
                        },
                        new
                        {
                            Id = 9L,
                            IsActive = true,
                            Name = "هزینه سیستم تصفیه آب"
                        },
                        new
                        {
                            Id = 10L,
                            IsActive = true,
                            Name = "هزینه آب"
                        },
                        new
                        {
                            Id = 11L,
                            IsActive = true,
                            Name = "هزینه پراید"
                        },
                        new
                        {
                            Id = 12L,
                            IsActive = true,
                            Name = "هزینه نیسان"
                        },
                        new
                        {
                            Id = 13L,
                            IsActive = true,
                            Name = "هزینه ایاب ذهاب"
                        });
                });

            modelBuilder.Entity("madan.MVC.Data.Models.MaterialWithdrawal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("WithdrawerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MaterialWithdrawals");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.MaterialWithdrawalPay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MaterialWithdrawalId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialWithdrawalId");

                    b.ToTable("MaterialWithdrawalPays");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Name = "شسته"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Name = "بادامی"
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Name = "مخلوط"
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Name = "نخودی طبیعی"
                        },
                        new
                        {
                            Id = 5L,
                            IsActive = true,
                            Name = "نخودی شکسته"
                        },
                        new
                        {
                            Id = 6L,
                            IsActive = true,
                            Name = "سرندی"
                        },
                        new
                        {
                            Id = 7L,
                            IsActive = true,
                            Name = "قلوه سنگ"
                        },
                        new
                        {
                            Id = 8L,
                            IsActive = true,
                            Name = "ماسه شکسته"
                        },
                        new
                        {
                            Id = 9L,
                            IsActive = true,
                            Name = "پشت سرندی"
                        });
                });

            modelBuilder.Entity("madan.MVC.Data.Models.ProductPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.Withdrawer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Withdrawers");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.MaterialWithdrawalPay", b =>
                {
                    b.HasOne("madan.MVC.Data.Models.MaterialWithdrawal", "MaterialWithdrawal")
                        .WithMany("MaterialWithdrawalPays")
                        .HasForeignKey("MaterialWithdrawalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialWithdrawal");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.ProductPrice", b =>
                {
                    b.HasOne("madan.MVC.Data.Models.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.MaterialWithdrawal", b =>
                {
                    b.Navigation("MaterialWithdrawalPays");
                });

            modelBuilder.Entity("madan.MVC.Data.Models.Product", b =>
                {
                    b.Navigation("ProductPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
